Web/Models/JobApplicationModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class JobApplicationModel
    {
        [Required(ErrorMessage = "Please fill out your name.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your e-mail.")]
        [EmailAddress(ErrorMessage = "The e-mail address is invalid.")]
        [DisplayName("E-mail")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please write a short message about yourself.")]
        [DisplayName("Cover letter")]
        public string Cover { get; set; }

        [Required(ErrorMessage = "Please upload your CV.")]
        [DisplayName("Upload CV")]
        public HttpPostedFileBase CVFile { get; set; }
    }
}

Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Abstract;
using Domain.Configuration;
using Domain.Entities;

namespace Web.Controllers
{
    public class AdminController : Controller
    {
        private IRepository<JobApplication> _repository;

        public AdminController(IRepository<JobApplication> repository)
        {
            _repository = repository;
        }

        public ActionResult Applications()
        {
            var model = _repository.All();
            return View(model);
        }

        public ActionResult Settings()
        {
            return View();
        }

        public PartialViewResult AllowedFileTypes()
        {
            return PartialView("AllowedFileTypes");
        }

        public RedirectToRouteResult EnableExtension(FileTypes type)
        {
            Domain.Configuration.Settings.AllowedFileTypes.Add(type);
            return RedirectToAction("AllowedFileTypes");
        }

        public RedirectToRouteResult DisableExtension(FileTypes type)
        {
            Domain.Configuration.Settings.AllowedFileTypes.Remove(type);
            return RedirectToAction("AllowedFileTypes");
        }
    }
}

Web/Controllers/CVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain;
using Domain.Abstract;
using Domain.Entities;
using Domain.Enums;
using Web.Mappers;
using Web.Models;

namespace Web.Controllers
{
    public class CVController : Controller
    {
        private readonly ApplicationSubmitter _submitter;
        private readonly IRepository<JobApplication> _repository; 

        public CVController(ApplicationSubmitter submitter, IRepository<JobApplication> repository)
        {
            _submitter = submitter;
            _repository = repository;
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(JobApplicationModel model)
        {
            if (ModelState.IsValid)
            {
                var mapped = JobApplicationMapper.Map(model);
                var result = _submitter.Submit(mapped);
                if (result == SubmissionErrors.InvalidExtension)
                    ModelState.AddModelError("CVFile", "Invalid Extension for CV");
                if (result == SubmissionErrors.MissingCV)
                    ModelState.AddModelError("CVFile", "Empty CV");

                if (result == SubmissionErrors.None)
                    return RedirectToAction("Success");
            }


            return View(model);
        }

        public ViewResult Success()
        {
            return View();
        }

        public FileResult Download(string name, string filename)
        {
            var file = _repository.Get(x => x.Name == name && x.FileName == filename).FirstOrDefault();
            if(file != null)
                return new FileContentResult(file.CV, "application/pdf");
            return null;
        }
    }
}

Web/Views/Admin/AllowedFileTypes.cshtml
@using Domain.Configuration
<section id="allowedFileTypes">
    <ul>
        @foreach (FileTypes item in Enum.GetValues(typeof (FileTypes)))
        {
            <li>
                @item.ToString() 
                @{
                    var enabled = Settings.AllowedFileTypes.Contains(item);
                }

                @Ajax.ActionLink(enabled ? "Disable" : "Enable", enabled ? "DisableExtension" : "EnableExtension", "Admin", new { type = item }, new AjaxOptions(){ UpdateTargetId = "allowedFileTypes", InsertionMode = InsertionMode.Replace})

            </li>
        }
    </ul>
</section>

Web/Views/Admin/Applications.cshtml
@model System.Collections.Generic.List<Domain.Entities.JobApplication>

@{
    ViewBag.Title = "Applications";
}

<h2>Applications</h2>

@foreach (var item in Model)
{
    <article>
        <header>
            <h2>@item.Name</h2>
        </header>
        <section>
            @item.Email
        </section>
        <section>
            <p>@item.Cover</p>
        </section>
        <section>
            <a href="@Url.Action("Download", "CV", new { item.Name, item.FileName })">Download CV</a>
        </section>
    </article>
}

Web/Views/Admin/Settings.cshtml
@using Domain.Configuration
@model dynamic

@{
    ViewBag.Title = "Settings";
}

<article>
    <header>
        <h2>Allowed file types</h2>
    </header>
    @Html.Partial("AllowedFileTypes")
</article>

Web/Views/CV/Success.cshtml
@model dynamic

@{
    ViewBag.Title = "Success";
}

<article>
    <header>
        <h1>Success!</h1>
    </header>
    <section>
        <p>
            Your application has been submitted. We will contact you shortly.
        </p>
    </section>
</article>

Web/Views/CV/Upload.cshtml
@using System.Reflection
@using Domain.Configuration
@using Library.Attributes
@model Web.Models.JobApplicationModel

@{
    ViewBag.Title = "Upload";
}

@using (Html.BeginForm("Upload", "CV", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <article>
        <header>
            <h1>Upload your CV</h1>
        </header>
        <section>             
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </section>
        <section>
            @Html.LabelFor(x => x.Email)
            @Html.EditorFor(x => x.Email)
            @Html.ValidationMessageFor(x => x.Email)
        </section>
        <section>
            @Html.LabelFor(x => x.Cover)
            @Html.TextAreaFor(x => x.Cover)
            @Html.ValidationMessageFor(x => x.Cover)
        </section>
        <section>
            @Html.LabelFor(x => x.CVFile)
            <input type="file" name="CVFile" id="CVFile" />
            @Html.ValidationMessageFor(x => x.CVFile)
        </section>
        <section>
            @Html.Label("Extensions:")
            @{
                var list = new List<string>();
                foreach (var item in Settings.AllowedFileTypes)
                {
                    var fi = item.GetType().GetField(item.ToString());
                    var attribute = (FileAttribute)fi.GetCustomAttribute(typeof(FileAttribute), true);
                    list.Add("*." + attribute.Extension);
                }
            }
            @string.Format("({0})", string.Join(",", list))
        </section>
        <footer>
            <input type="submit"/>
        </footer>
    </article>
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>StormID CV Upload - @ViewBag.Title</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="~/Content/normalize.min.css">
        <link rel="stylesheet" href="~/Content/main.css">
        <link rel="stylesheet" href="~/Content/Site2.css"/>
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <div class="header-container">
            <header class="wrapper clearfix">
                <h1 class="title">StormID CV Upload Form</h1>
                <nav>
                    <ul>
                        <li><a href="@Url.Action("Upload", "CV")">Upload CV</a></li>
                        <li><a href="@Url.Action("Applications", "Admin")">Applications</a></li>
                        <li><a href="@Url.Action("Settings", "Admin")">Settings</a></li>
                    </ul>
                </nav>
            </header>
        </div>

        <div class="main-container">
            <div class="main wrapper clearfix">
                @RenderBody()
            </div> 
        </div>

        <div class="footer-container">
            <footer class="wrapper">

            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryval")
    </body>
</html>